### ISSUE TITLE
Infografia_IrvingFernando

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/infografia-de-las-librerias-Practica-interfaz-visual-studio#2]
[Infografia_IrvingFernandoReyesPacheco.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-IrvingFernando/files/8346453/Infografia_IrvingFernandoReyesPacheco.pdf)

**Comment by Sandra631** [comment]
20% Bien hecho.

**Comment by josealfredo79** [comment]
bien hecho y revisado...
